ktor:
  deployment:
    port: ${?HTTP_PORT}
    sslPort: ${?HTTPS_PORT}
  application:
    modules:
      - com.olds.RoutingKt.module
  security:
    ssl:
      keyStore: ${?SSL_KEYSTORE_PATH}
      keyAlias: ${?SSL_KEY_ALIAS}
      keyStorePassword: ${?SSL_KEYSTORE_PASSWORD}
      privateKeyPassword: ${?SSL_PRIVATE_KEY_PASSWORD}
    jwt:
      realm: todo-api
      issuer: todo-api
      audience: todo-api
      secret: ${?JWT_SECRET}
  sqlserver:
    url: ${?SQLSERVER_JDBC_URL}
    username: ${?SQLSERVER_USERNAME}
    password: ${?SQLSERVER_PASSWORD}
  redis:
    url: ${?REDIS_URL}