ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.olds.RoutingKt.module
  security:
    jwt:
      realm: todo-api
      issuer: todo-api
      audience: todo-api
      secret: ${?JWT_SECRET}
  redis:
    url: ${?REDIS_URL}